#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any


def pct(value: Any) -> str:
    return "N/A" if value is None else f"{float(value):.2f}"


def rate(value: Any) -> str:
    return "N/A" if value is None else f"{float(value) * 100:.2f}%"


def load_index(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        rows = list(csv.DictReader(handle, delimiter="\t"))
    if not rows:
        raise ValueError(f"No runs in index: {path}")
    return rows


def load_metrics(run_dir: Path) -> dict[str, Any]:
    path = run_dir / "metrics.json"
    if not path.exists():
        raise FileNotFoundError(path)
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Summarize frozen Judge v04 Balanced runs for Rewriters v01-v04."
    )
    parser.add_argument(
        "--index",
        default="runs/judge_v04_balanced_run_index.tsv",
        help="TSV generated by run_frozen_judge_v04_all.sh",
    )
    parser.add_argument(
        "--output-dir",
        default="runs/judge_v04_balanced_comparison",
    )
    args = parser.parse_args()

    index_path = Path(args.index).expanduser().resolve()
    output_dir = Path(args.output_dir).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    result_rows: list[dict[str, Any]] = []
    for row in load_index(index_path):
        run_dir = Path(row["run_dir"]).expanduser()
        if not run_dir.is_absolute():
            run_dir = (Path.cwd() / run_dir).resolve()
        metrics = load_metrics(run_dir)
        overall = metrics["overall"]
        local = metrics["local_repair"]
        recon = metrics["proposition_reconstruction"]
        result_rows.append(
            {
                "version": row["version"],
                "overall_quality": overall["quality_score"],
                "macro_quality": metrics["macro_quality_score"],
                "debiasing": overall["debiasing_score"],
                "naturalness": overall["naturalness_score"],
                "type_specific": overall["type_specific_score"],
                "local_quality": local["quality_score"],
                "reconstruction_quality": recon["quality_score"],
                "pass_rate": overall["pass_rate"],
                "partial_rate": overall["partial_rate"],
                "fail_rate": overall["fail_rate"],
                "errors": overall["error_count"],
                "count": overall["count"],
                "run_dir": str(run_dir),
            }
        )

    order = {"v01": 1, "v02": 2, "v03": 3, "v04": 4}
    result_rows.sort(key=lambda row: order.get(str(row["version"]), 99))

    csv_path = output_dir / "judge_v04_balanced_comparison.csv"
    with csv_path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(result_rows[0].keys()))
        writer.writeheader()
        writer.writerows(result_rows)

    table_rows = []
    for row in result_rows:
        table_rows.append(
            "| {version} | {overall} | {macro} | {debiasing} | {naturalness} | "
            "{type_specific} | {local} | {recon} | {pass_rate} | {partial_rate} | "
            "{fail_rate} | {errors}/{count} |".format(
                version=str(row["version"]).upper(),
                overall=pct(row["overall_quality"]),
                macro=pct(row["macro_quality"]),
                debiasing=pct(row["debiasing"]),
                naturalness=pct(row["naturalness"]),
                type_specific=pct(row["type_specific"]),
                local=pct(row["local_quality"]),
                recon=pct(row["reconstruction_quality"]),
                pass_rate=rate(row["pass_rate"]),
                partial_rate=rate(row["partial_rate"]),
                fail_rate=rate(row["fail_rate"]),
                errors=row["errors"],
                count=row["count"],
            )
        )

    markdown = """# Frozen Judge v04 Balanced Comparison

All systems are evaluated with the same frozen Judge prompt, scoring rules, weights, and rewrite-type map.

| Rewriter | Overall | Macro | Debiasing | Naturalness | Fidelity/Relevance | Local | Reconstruction | PASS | PARTIAL | FAIL | Errors |
|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|
{rows}

Scoring weights: Debiasing 50%, Naturalness 25%, type-specific metric 25%.
""".format(rows="\n".join(table_rows))

    md_path = output_dir / "judge_v04_balanced_comparison.md"
    md_path.write_text(markdown, encoding="utf-8")

    print(markdown)
    print(f"CSV: {csv_path}")
    print(f"Markdown: {md_path}")


if __name__ == "__main__":
    main()
